/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  CompanyInput,  LinkedInPostResponse,  Resume } from "../types"

import type * as types from "../types"

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "ExtractResume" BAML action.
 *
 * This server action calls the underlying BAML function "ExtractResume"
 * with the specified parameters.
 *
 * @param { string } resume - Input parameter.
 *
 * @returns {Promise<types.Resume>} A promise that resolves with the result of the action.
 */
export const ExtractResume = async (
  resume: string,
): Promise<types.Resume> => {
  return b.ExtractResume(
    resume,
  );
};

/**
 * Executes the "GeneratePost" BAML action.
 *
 * This server action calls the underlying BAML function "GeneratePost"
 * with the specified parameters.
 *
 * @param { types.CompanyInput } input - Input parameter.
 *
 * @returns {Promise<types.LinkedInPostResponse>} A promise that resolves with the result of the action.
 */
export const GeneratePost = async (
  input: types.CompanyInput,
): Promise<types.LinkedInPostResponse> => {
  return b.GeneratePost(
    input,
  );
};